#!/usr/bin/env python3

import sys
import urllib.request

if len(sys.argv) < 2:
    print("Missing output filename")
    sys.exit(1)

filename = sys.argv[1]

domains = {}

output = []

with urllib.request.urlopen("https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts") as response:
    body = response.read().decode().splitlines()

    for line in body:
        # Remove comments
        position = line.find("#")
        if position != -1:
            line = line[:position]

        if not line.strip():
            continue

        try:
            addr, hostname = line.split()
        except Exception as e:
            print(e, "'{}'".format(line))
            break

        # Filter out useless entries
        if addr != "0.0.0.0" or hostname == "0.0.0.0":
            continue

        output.append("""local-zone: "{}" always_nxdomain""".format(hostname))

with open(filename, "w") as f:
    f.write("\n".join(output))
