---

name: build images

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: make blacklist
        run: make blacklist

      - name: build unbound
        run: |
          docker buildx build \
            --tag pluggi/unbound:latest \
            --platform linux/amd64,linux/arm/v7 \
            --push \
            unbound/

      - name: build dhcpd
        run: |
          docker buildx build \
            --tag pluggi/dhcpd:latest \
            --platform linux/amd64,linux/arm/v7 \
            --push \
            dhcpd/
